#ifndef BRE_ERR_H
#define BRE_ERR_H

/*************************************************************************
*           This file was generated by pintfdef from bre_err.c
*           Revision: Unknown
**************************************************************************
****** DO NOT MODIFY ANYTHING OUTSIDE OF THE 'CUSTOMIZATIONS' BLOCK ******
**************************************************************************/

/* CUSTOMIZATIONS BELOW */

#define BRE_MSGSET 60

/* CUSTOMIZATIONS ABOVE */


   void
bre_clear_errors(void);


   int
bre_error_count(void);


/*----------------------------------------------------------------------
 *
 * Print an error message.
 * This causes the parse to be aborted immediately.
 *
 */
   void
Bre_Parse_Error(
	MSG_SET_060 msgcode,
	...);


/*----------------------------------------------------------------------
 * Print an parse warning message.
 * Warning message still prevents success, but
 * a warning does not immediately halt
 *
 */
   void
Bre_Parse_Warn(
	MSG_SET_060 msgcode,
	...);


/*----------------------------------------------------------------------
 * Print a message.
 * Use this function to warn the user.
 *
 */
   void
Bre_Parse_Message(
	MSG_SET_060 msgcode,
	...);


/*----------------------------------------------------------------------
 * Print an error message.
 * This error function is for internal, or serious errors
 * not related to parsing. It will immediately
 * cause return to the calling application with
 * some kind of error indication.
 *
 */
   void
Bre_Error(
	MSG_SET_060 msgcode,
	...);

#endif /* BRE_ERR_H */
